print("Nama : Flavia Fayyazza A.A.")
print("NIM : I0322047")
print("Asal : Surakarta")
print("==============================")
print("Saya berasal dari Kota Surakarta atau lebih dikenal dengan sebutan Kota Solo.")
print("Kota Solo merupakan kota asal presiden kita. Selain itu di Kota Solo juga terdapat dua keraton")
print("Keraton tersebut adalah Keraton Kasunanan Surakarta dan Pura Mangkunegaran")
print("Keraton tersebut masih sering menggelar acara adat")
print("Beberapa acara tersebut adalah sekaten, grebeg, kirab, dan lain lain.")
print("=========================================================================")
print("Lalu harapan saya sebagai lulusan TI adalah saya bisa memiliki skill di berbagai bidang")
print("___________________________________________________________________________________________")